const { withPodfile, withPodfileProperties } = require('@expo/config-plugins');

const DEPLOYMENT_TARGET = '16.4';
const START_MARKER = '# @generated by withIosDeploymentTarget';
const END_MARKER = '# @end withIosDeploymentTarget';

const POD_TARGET_FIX = `
    ${START_MARKER}
    # Xcode 27 rejects dependency targets below iOS 15. Some podspec resource
    # targets still declare iOS 9/12/13, so clamp only those older targets.
    minimum_ios_version = Gem::Version.new(podfile_properties['ios.deploymentTarget'] || '${DEPLOYMENT_TARGET}')
    installer.pods_project.targets.each do |pod_target|
      pod_target.build_configurations.each do |config|
        current_version = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current_version.nil? || Gem::Version.new(current_version) < minimum_ios_version
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_ios_version.to_s
        end
      end
    end
    ${END_MARKER}
`;

function addPodTargetFix(contents) {
  if (contents.includes(START_MARKER)) return contents;

  const postInstallCall = /(\s+react_native_post_install\([\s\S]*?^\s+\)\n)/m;
  if (!postInstallCall.test(contents)) {
    throw new Error('Could not find react_native_post_install in ios/Podfile');
  }

  return contents.replace(postInstallCall, `$1${POD_TARGET_FIX}`);
}

module.exports = function withIosDeploymentTarget(config) {
  config = withPodfileProperties(config, (config) => {
    config.modResults['ios.deploymentTarget'] = DEPLOYMENT_TARGET;
    return config;
  });

  return withPodfile(config, (config) => {
    config.modResults.contents = addPodTargetFix(config.modResults.contents);
    return config;
  });
};
